name: Release Workflow

on:
  release:
    types: [published]

jobs:
  release-builds:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          brew install cmake
          brew install gmp
          brew install bison
          brew install flex
          echo "/opt/homebrew/opt/flex/bin:/opt/homebrew/opt/bison/bin" >> "$GITHUB_PATH"

      - name: Build project
        run: |
          ./ci/build_maximally_static.sh
          
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./build-static/golem.tar.bz2 
          name: golem-arm-osx.tar.bz2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
