name: Release Workflow

on:
  release:
    types: [published]

jobs:
  release-builds:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          brew install cmake
          brew install gmp
          brew install bison
          brew install flex
          echo "/opt/homebrew/opt/flex/bin:/opt/homebrew/opt/bison/bin" >> "$GITHUB_PATH"

      - name: Build project
        run: |
          ./ci/build_maximally_static.sh
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: golem-arm-osx.tar.bz2
          path: ./golem-arm-osx.tar.bz2

