name: Release Workflow

on:
  release:
    types: [created]

jobs:
  release-builds:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          echo "HOMEBREW_NO_AUTO_UPDATE=1" >> $BASH_ENV
          brew install cmake
          brew install gmp
          brew install bison
          brew install flex
          echo 'export PATH=/opt/homebrew/opt/flex/bin:/opt/homebrew/opt/bison/bin:$PATH' >> $BASH_ENV

      - name: Build project
        run: |
          ./ci/build_maximally_static.sh
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: golem-arm-osx.tar.bz2
          path: ./golem-arm-osx.tar.bz2

